spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true

logging:
    pattern:
        file: "%d{HH:mm:ss} %-5p [%c] - %m%n"

    level:
        ROOT: error
        org.springframework: info
        javax.faces: info
        org.omnifaces: info
        org.springframework.security: warn
        org.hibernate: warn
        org.hibernate.type.descriptor.sql: warn
    file:
        name: c:\temp\app.log